### ISSUE TITLE
No funciona el monitor

### ISSUE THREAD

**Issue by ddiaz2380** [gerardet46/dotfiles#1]
Hola estuve probando tus dots en una vm funcono todo o y me gusta mucho. Procedo a instalar físico, installo artix runit perfecto y luego corros los dos .sh todo bien sin errores, al iniciar dwm no corre el monitor. Cual es e problema o error?
Gracias!

**Comment by gerardet46** [comment]
Hola, el script para cambiar el monitor (sc/monitors) solo irá bien si los identificadores de los monitores son exactamente los mismos que los que tengo yo (cosa que dudo). Para configurarlos, recomiendo usar arandr y configurar allí los monitores. Allí te permite ver también los nombres de los monitores para sustituirlos en el script.

También se puede usar "xrandr | grep connected" para ver los monitores disponibles.

**Comment by ddiaz2380** [comment]
Gracias ya lo solucione... pero ahora tengo problemas con el audio ajajajaj ya me anda todo salvo el audio. Cambie a OpenRC porque lo conosco un poco mas, asi que espero tener mejor suerte, la dwmblocks no muestra algunos iconos y supongo que sera la fuente, ya vere eso, quiero solucionar el audio y ya estaria con eso. Muchas gracias.
